### ISSUE TITLE
GAME_DEBUG define as compile flag

### ISSUE THREAD

**Issue by approxit** [tehKaiN/ACE#14]
Right now we have GAME_DEBUG flag hardcoded inside source files.
It's changes results in git. To make a prod you need to switch it's value on and off.

Better idea is to move this flag to compile flags.

**Comment by tehKaiN** [comment]
Could be solved by #17

**Comment by tehKaiN** [comment]
Should be changed to ACE_DEBUG since I can imagine scenarios where only debugging is enabled on ACE level, only on game level, on both or on none.
