### ISSUE TITLE
Implement custom FS function wrappers

### ISSUE THREAD

**Issue by tehKaiN** [tehKaiN/ACE#25]
There are no stdc functions for reading directories, so to omit POSIX lib dependency ACE needs its own directory fns based on OS fns.

Also, wrapping around fopen will give us ability to setup file access based on OS files/dirs or one monolithic big file. This will also reduce disk usage 'cuz Amiga FSs are inefficient as hell with many small files.

- [x] Implement directory fns with similar syntax to `opendir` / `readdir` / `closedir`
- [x] Wrap around file access fns: `fopen`, `close`, `fseek`, `ftell`, `fread`, `fwrite`
- [ ] Add ability to work on plain file structure of host OS or on virtual FS based on monolithic file.

**Comment by tehKaiN** [comment]
There is some directory reading in OpenFire in menu's map list. This could be used as example of using OS fns.

**Comment by tehKaiN** [comment]
Needed for https://github.com/tehKaiN/ACE/issues/31 because file read from HDD needs OS - file wrappers should re-enable OS until access is done.

**Comment by approxit** [comment]
I think that these two cases can be handled with semiautomatic system enabling/disabling.

If your code want to have OS disabled at all times you just disable it as soon as possible in your code.
Then, when you require something from files, OS should be turned on only temporary for single file call and closed after, automagically. Of course it would be not optimized for multiple file calls in row, like for loading states. To avoid this you can explicitly turn on system by function before file calls sequence, and then explicitly turn off.

File API should check system state and it turn on when needed, and turn it off only when system was already on. You don't even need any change in standard file API.

**Comment by approxit** [comment]
And what exactly would give you some kind of file modificator per file handle, when you have problem with handling MULTIPLE files in short period?

Is that additional flag in "rw" stuff would tell "wait a sec, keep system up, we're gonna write some files in next 10 instructions ahead"? I guess no.

System turning on/off is amiga specific. You can't avoid some code to make better performance on that architecture. Stacking OS turns on/off is actually not needed. Simple boolean in system manager would do the job.

**Comment by tehKaiN** [comment]
Okay, multiple file case has a point against introducing such feature. Such file flag would only minimize performance impact, but not get rid of it. However, OS usage stacking is required.

Enabling OS during file access and/or mem alloc is required since otherwise ACE would hang, so forcing OS enabling is needed. Then you need higher level means to enable OS for longer periods for OS usage optimizations such as files. Then such OS-optimized fn may get called by other fn which could also disable OS for optimizing rest of its stuff. This all refers to design such that OS is normally disabled, which IMO makes sense because most of the time ACE behaves better without OS. Even more, lots of functionality won't work when OS is enabled (keyboard, timing, blitter).

**Comment by tehKaiN** [comment]
Directory traversal has been implemented in 0f04a3fb33f0e207b096e08aa5bf05dbf8c53ea9. I'll move monolithic FS to separate issue since it's not needed atm
