### ISSUE TITLE
Showcase examples includes config.h

### ISSUE THREAD

**Issue by grovdata** [tehKaiN/ACE#39]
This file seems to have been deleted a while back, so right now `make showcase` doesn't build.

https://github.com/tehKaiN/ACE/blob/126533d8b6470d2f760889049d2eebe7f431c0c5/showcase/src/input.h#L7

https://github.com/tehKaiN/ACE/blob/1b540f652151ec280a8b7e0a65d4dae0032c8f71/showcase/src/main.c#L11

**Comment by tehKaiN** [comment]
Sorry for that, will be fixed tomorrow ;)

**Comment by tehKaiN** [comment]
Showcase compilation is fixed. It was supposed to show ACE features using minimal and not quite code, but noone really has time and/or will to expand it. There are only 3-5 things that are done. If you really want to see ACE in action, try hacking through one of [games created using ACE](https://github.com/tehKaiN/ACE#games-created-using-ace). It's still quite nice starting point without too much code to read. ;)
