### ISSUE TITLE
Wiki vs "doc" folder

### ISSUE THREAD

**Issue by tehKaiN** [tehKaiN/ACE#54]
We should determine if we use wiki or docs folder. Here's [some arguments](https://www.dzombak.com/blog/2015/03/Why-use-GitHub-Wikis-.html) against wiki.

If we're dropping wiki, [relative links](https://blog.github.com/2013-01-31-relative-links-in-markup-files/) will come in handy.

- [x] Decide whether we use wiki or `doc` folder
- [ ] Port all wiki content to `doc` folder, if wiki is going to be scrapped

**Comment by approxit** [comment]
+1 for `/docs` folder instead of "external" source for documentation.

**Comment by tehKaiN** [comment]
We'll migrate to `docs` folder then.
